# Generated by Django 4.2.3 on 2023-07-13 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['-longest_streak', '-created']},
        ),
        migrations.RemoveField(
            model_name='habit',
            name='checked',
        ),
        migrations.AlterField(
            model_name='habit',
            name='last_check',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 13, 19, 43, 26, 769156)),
        ),
    ]
